app/items/models.py
from sqlalchemy import Column, ForeignKey, Integer, String
from sqlalchemy.orm import relationship
from app import Base
from app.auth.models import User
from app.catalog.models import Category


class Item(Base):
    __tablename__ = 'item'

    name = Column(String(80), nullable=False)
    id = Column(Integer, primary_key=True)
    description = Column(String(250))
    category_id = Column(Integer, ForeignKey('category.id'))
    category = relationship(Category)
    user_id = Column(Integer, ForeignKey('user.id'))
    user = relationship(User)

    @property
    def serialize(self):
        """Return object data in easily serializeable format"""
        return {
            'name': self.name,
            'description': self.description,
            'category_id': self.category_id,
            'user_id': self.user_id,
            'id': self.id
        }

app/catalog/controllers.py
# Import flask dependencies
from flask import Blueprint, request, render_template, \
    flash, redirect, url_for, session as login_session

# Import the database session from the main app module
from app import session, app
from sqlalchemy import asc, desc

# Import module models
from app.catalog.models import Category
from app.items.models import Item

# Define the blueprint: 'catalog', set its url prefix: app.url/catalog
catalogBlueprint = Blueprint('catalog', __name__, url_prefix='/catalog')


# Set the route and accepted methods
@app.route('/', methods=['GET'])
@catalogBlueprint.route('/', methods=['GET'])
def showCatalog():
    catalog = session.query(Category).order_by(asc(Category.name))
    latestItems = session.query(Item.name, Item.id, Category.name, Category.id).join(Category).order_by(
        desc(Item.id)).limit(10)

    latest = []
    for (itemName, itemId, categoryName, categoryId) in latestItems:
        latest.append(
            {'item_name': itemName, 'category_name': categoryName, 'item_id': itemId, 'category_id': categoryId})
    return render_template('catalog/catalog.html', catalog=catalog, latest=latest)


@catalogBlueprint.route('/newCategory', methods=['GET', 'POST'])
def newCategory():
    if 'username' not in login_session:
        return redirect(url_for('auth.showLogin'))
    if request.method == 'POST':
        if request.form['name']:
            newCategory = Category(name=request.form['name'], user_id=login_session['user_id'])
            session.add(newCategory)
            flash('New Category %s Successfully Created' % newCategory.name)
            session.commit()
            return redirect(url_for('catalog.showCatalog'))
        else:
            flash('Name is mandatory')
            return render_template('catalog/newcategory.html')
    else:
        return render_template('catalog/newcategory.html')


@catalogBlueprint.route('/<category_name>/edit', methods=['GET', 'POST'])
def editCategory(category_name):
    if 'username' not in login_session:
        return redirect(url_for('auth.showLogin'))
    editedCategory = session.query(Category).filter_by(name=category_name).one()
    if editedCategory.user_id != login_session['user_id']:
        return "<script>function myFunction() {alert('You are not authorized to edit this category. Please create your own category in order to edit.');}</script><body onload='myFunction()''>"

    if request.method == 'POST':
        if request.form['name']:
            editedCategory.name = request.form['name']
            flash('Category Successfully Edited %s' % editedCategory.name)
            return redirect(url_for('catalog.showCatalog'))
        else:
            flash('Name is mandatory')
            return render_template('catalog/editcategory.html', category=editedCategory)
    else:
        return render_template('catalog/editcategory.html', category=editedCategory)


@catalogBlueprint.route('/<category_name>/delete', methods=['GET', 'POST'])
def deleteCategory(category_name):
    if 'username' not in login_session:
        return redirect(url_for('auth.showLogin'))
    categoryToDelete = session.query(Category).filter_by(name=category_name).one()
    print categoryToDelete.user_id
    if categoryToDelete.user_id != login_session['user_id']:
        return "<script>function myFunction() {alert('You are not authorized to delete this category. Please create your own category in order to delete.');}</script><body onload='myFunction()''>"

    if request.method == 'POST':
        session.delete(categoryToDelete)
        flash('%s Successfully Deleted' % categoryToDelete.name)
        session.commit()
        return redirect(url_for('catalog.showCatalog'))
    else:
        return render_template('catalog/deletecategory.html', item=categoryToDelete)


@catalogBlueprint.route('/<category_name>/items')
def showItems(category_name):
    catalog = session.query(Category).order_by(asc(Category.name))
    category = session.query(Category).filter_by(name=category_name).one()
    items = session.query(Item).filter_by(category_id=category.id).all()
    return render_template('items/items.html', catalog=catalog, items=items, category=category)


@catalogBlueprint.route('/<category_name>/<item_name>', methods=['GET'])
def showItem(category_name, item_name):
    item = session.query(Item).filter_by(name=item_name).one()
    return render_template('items/item.html', item=item)

app/items/controllers.py
# Import flask dependencies
from flask import Blueprint, request, render_template, \
    flash, g, redirect, url_for, session as login_session

# Import the database session from the main app module
from app import session

from sqlalchemy import asc

# Import module models
from app.catalog.models import Category
from app.items.models import Item

# Define the blueprint: 'item', set its url prefix: app.url/catalog
itemBlueprint = Blueprint('item', __name__, url_prefix='/catalog')


# Set the route and accepted methods

@itemBlueprint.route('/newItem', methods=['GET', 'POST'])
def newItem():
    if 'username' not in login_session:
        return redirect(url_for('auth.showLogin'))
    categories = session.query(Category).order_by(asc(Category.name))
    if request.method == 'POST':
        if request.form['name'] and request.form['description'] and request.form['category_id']:
            newItem = Item(name=request.form['name'],
                           description=request.form['description'],
                           category_id=request.form['category_id'],
                           user_id=login_session['user_id'])
            session.add(newItem)
            session.commit()
            flash('New Item %s Successfully Created' % (newItem.name))
            return redirect(url_for('catalog.showCatalog'))
        else:
            flash('All fields are mandatory')
            return render_template('items/newitem.html', categories=categories)
    else:
        return render_template('items/newitem.html', categories=categories)


@itemBlueprint.route('/item/<item_name>/edit', methods=['GET', 'POST'])
def editItem(item_name):
    if 'username' not in login_session:
        return redirect(url_for('auth.showLogin'))
    categories = session.query(Category).order_by(asc(Category.name))
    editedItem = session.query(Item).filter_by(name=item_name).one()
    if editedItem.user_id != login_session['user_id']:
        return "<script>function myFunction() {alert('You are not authorized to edit this item. Please create your own item in order to edit.');}</script><body onload='myFunction()''>"

    if request.method == 'POST':
        if request.form['name'] and request.form['description'] and request.form['category_id']:
            editedItem.name = request.form['name']
            editedItem.description = request.form['description']
            editedItem.category_id = request.form['category_id']
            session.add(editedItem)
            session.commit()
            flash('Item Successfully Edited')
            return redirect(url_for('catalog.showCatalog'))
        else:
            flash('All fields are mandatory')
            return render_template('items/edititem.html', item=editedItem, categories=categories)
    else:
        return render_template('items/edititem.html', item=editedItem, categories=categories)


@itemBlueprint.route('/item/<item_name>/delete', methods=['GET', 'POST'])
def deleteItem(item_name):
    if 'username' not in login_session:
        return redirect(url_for('auth.showLogin'))
    itemToDelete = session.query(Item).filter_by(name=item_name).one()

    if itemToDelete.user_id != login_session['user_id']:
        return "<script>function myFunction() {alert('You are not authorized to delete this item. Please create your own item in order to delete.');}</script><body onload='myFunction()''>"

    if request.method == 'POST':
        session.delete(itemToDelete)
        session.commit()
        flash('Item Successfully Deleted')
        return redirect(url_for('catalog.showCatalog'))
    else:
        return render_template('items/deleteitem.html', item=itemToDelete)

app/templates/items/deleteitem.html
{% extends "main.html" %}
{% block content %}
{% include "header.html" %}

<div class="container-fluid" >
   <div class="row">
	    <h1>Delete Item</h1>

	    <p> Are you sure you want to delete {{item.name}}? </p>

		<form action="#" method='post'>
			<input name="_csrf_token" type=hidden value="{{ csrf_token() }}">
			<button type="submit" class="btn btn-default delete" id="submit" type="submit">
			<span class="glyphicon glyphicon-trash" aria-hidden="true"></span> Delete</button>
			<a href="{{url_for('catalog.showCatalog')}}" class="btn btn-default delete">
				<span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Cancel
			</a>
		</form>
   </div>

</div>

{% endblock %}

app/templates/items/edititem.html
{% extends "main.html" %}
{% block content %}
{% include "header.html" %}

   <div class="container-fluid" >
        <div class="row">
			<div class="col-md-4">
				<h1>Edit Item: {{item.name}}</h1>
				<br/>

				<div class='flash error'>
					{% with messages = get_flashed_messages() %}
						{% if messages %}
							<ul>
								{% for message in messages %}
									<li> <strong> {{ message }} </strong> </li>
								{% endfor %}
							</ul>
						{% endif %}
					{% endwith %}
				</div>
				<form action="#" method = "post">
					<input name="_csrf_token" type=hidden value="{{ csrf_token() }}">
					<div class="form-group">
						<label for="name">Name:</label>
						<input type ="text" maxlength="100" class="form-control" name="name" value="{{item.name }}">

						<label for="description">Description:</label>
						<textarea class="form-control" maxlength="250" rows="3" name="description">{{item.description}}</textarea>

						<label for="category_id">Category:</label>
						<select class="form-control" name="category_id">
							<option value="">Select</option>
							 {% for category in categories %}
								<option value="{{category.id}}" {% if (category.id == item.category_id) %} selected="selected" {% endif %} > {{ category.name }} </option>
							 {% endfor %}
						</select>


						<div class="pt-15"></div>
						<button type="submit" class="btn btn-default" id="submit" type="submit">
							<span class="glyphicon glyphicon-ok" aria-hidden="true"></span> Save
						</button>
						<a href = "{{url_for('catalog.showCatalog')}}" class="btn btn-default delete">
							<span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Cancel
						</a>
					</div>
				</form>
			</div>
		</div>
	</div>
{% endblock %}

app/templates/items/item.html
{% extends "main.html" %}
{% block content %}
{% include "header.html" %}

<div class="container-fluid" >
   <div class="row">
	   <h2> {{item.name}} </h2>

	   <p>{{item.description}}</p>
       {% if 'username' in session %}
       <a href="{{url_for('item.editItem', item_name=item.name ) }}">Edit</a> |
       <a href="{{url_for('item.deleteItem', item_name=item.name ) }}">Delete</a>
       {% endif %}
   </div>

</div>

{% endblock %}

app/templates/items/items.html
{% extends "main.html" %}
{% block content %}
{% include "header.html" %}
    <div class="container-fluid" >
        <div class="row equal">
            <div class="col-md-3 border-right">
                {% if 'username' in session %}
                <a href="{{url_for('catalog.newCategory')}}">
                    <button class="btn btn-success" id="new-category">
                        <span aria-hidden="true"></span>Add Category
                    </button>
                </a>
                {% endif %}
                <h3>Categories</h3>
                {% for category in catalog %}
                    <a href="{{url_for('catalog.showItems', category_name = category.name)}}">
                        {{category.name}}
                    </a>
                {% endfor %}
            </div>
            <div class="col-md-9" >
                <div class="pl-10">
                    <h3>{{ category.name }} ({{items|length}} items)</h3>

                    {% if 'username' in session %}
                    <a href="{{url_for('catalog.editCategory', category_name=category.name)}}">Edit</a> |
                    <a href="{{url_for('catalog.deleteCategory', category_name=category.name)}}">Delete</a>
                    <br/><br/>
                    {% endif %}

					{% if items !=[] %}
                        {% for i in items %}
                            <a href="{{url_for('catalog.showItem',  category_name=category.name, item_name=i.name)}}">{{i.name}}</a>
                            <br/>
                        {% endfor %}
	                {% endif %}
                </div>
            </div>
        </div>
    </div>

{% endblock %}

app/templates/items/newitem.html
{% extends "main.html" %}
{% block content %}
{% include "header.html" %}

	<div class="container-fluid" >
        <div class="row">
			<div class="col-md-4">
				<h1>New Category Item</h1>
				<br/>

                <div class='flash error'>
					{% with messages = get_flashed_messages() %}
						{% if messages %}
							<ul>
								{% for message in messages %}
									<li> <strong> {{ message }} </strong> </li>
								{% endfor %}
							</ul>
						{% endif %}
					{% endwith %}
				</div>
				<form action="#" method="post">
					<input name="_csrf_token" type=hidden value="{{ csrf_token() }}">
					<div class="form-group">
						<label for="name">Name:</label>
						<input type ="text" maxlength="50" class="form-control" name="name"placeholder="Name of the item">

						<label for="description">Description:</label>
						<textarea class="form-control" maxlength="250" rows="3" name="description" placeholder="Description of the item"></textarea>

						<label for="category_id">Category:</label>
						<select class="form-control" name="category_id">
							<option value="">Select</option>
							 {% for category in categories %}
								<option value="{{category.id}}">{{category.name}}</option>
							 {% endfor %}
						</select>

						<div class="pt-15"></div>
						<button type="submit" class="btn btn-default" id="submit" type="submit">Create</button>
					</div>
				</form>
			</div>
		</div>
	</div>

{% endblock %}